# Generated by Django 5.0.6 on 2024-07-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lideranca_equipe', models.FileField(blank=True, null=True, upload_to='administrativo/')),
                ('reunioes_comerciais', models.FileField(blank=True, null=True, upload_to='administrativo/')),
                ('uniformes_crachas', models.FileField(blank=True, null=True, upload_to='administrativo/')),
                ('pagamento_boletos', models.FileField(blank=True, null=True, upload_to='administrativo/')),
                ('conta_bancaria_pj', models.FileField(blank=True, null=True, upload_to='administrativo/')),
                ('fluxo_caixa', models.FileField(blank=True, null=True, upload_to='administrativo/')),
                ('inadimplencia', models.FileField(blank=True, null=True, upload_to='administrativo/')),
                ('controle_balanco', models.FileField(blank=True, null=True, upload_to='administrativo/')),
                ('planejamento_orcamento', models.FileField(blank=True, null=True, upload_to='administrativo/')),
                ('orcamento_compartilhado', models.FileField(blank=True, null=True, upload_to='administrativo/')),
            ],
        ),
        migrations.CreateModel(
            name='Comercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cortesia_visitantes', models.FileField(blank=True, null=True, upload_to='comercial/')),
                ('participacao_mentoria', models.FileField(blank=True, null=True, upload_to='comercial/')),
                ('equipe_comercial_contratada', models.FileField(blank=True, null=True, upload_to='comercial/')),
                ('trilha_treinamento', models.FileField(blank=True, null=True, upload_to='comercial/')),
                ('participacao_encontros_lideres', models.FileField(blank=True, null=True, upload_to='comercial/')),
                ('funil_vendas_crm', models.FileField(blank=True, null=True, upload_to='comercial/')),
                ('pontuacao_cliente_oculto', models.FileField(blank=True, null=True, upload_to='comercial/')),
                ('participacao_campanhas', models.FileField(blank=True, null=True, upload_to='comercial/')),
                ('pesquisa_concorrentes', models.FileField(blank=True, null=True, upload_to='comercial/')),
                ('conversao_leads', models.FileField(blank=True, null=True, upload_to='comercial/')),
                ('politica_comissionamento', models.FileField(blank=True, null=True, upload_to='comercial/')),
                ('orcamento_mkt', models.FileField(blank=True, null=True, upload_to='comercial/')),
                ('profissional_mkt', models.FileField(blank=True, null=True, upload_to='comercial/')),
                ('entrega_kit_rematricula', models.FileField(blank=True, null=True, upload_to='comercial/')),
                ('entrega_kit_visita', models.FileField(blank=True, null=True, upload_to='comercial/')),
                ('leads_atraso_crm', models.FileField(blank=True, null=True, upload_to='comercial/')),
            ],
        ),
    ]
