# Generated by Django 5.0.6 on 2024-11-21 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glex', '0003_administrativo_usuario_modificacao'),
        ('ia', '0058_alter_processo_assunto_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dominio1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_implementation', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Program Implementation')),
                ('program_implementation_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio1/', verbose_name='Program Implementation (PDF)')),
                ('staffing_instructional_program', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Staffing the Instructional Program')),
                ('staffing_instructional_program_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio1/', verbose_name='Staffing the Instructional Program (PDF)')),
                ('resource_allocation', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Resource Allocation')),
                ('resource_allocation_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio1/', verbose_name='Resource Allocation (PDF)')),
                ('implementation_supervision_instructional_program', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Implementation and Supervision of the Instructional Program')),
                ('implementation_supervision_instructional_program_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio1/', verbose_name='Implementation and Supervision (PDF)')),
                ('professional_learning_opportunities', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Professional Learning Opportunities')),
                ('professional_learning_opportunities_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio1/', verbose_name='Professional Learning Opportunities (PDF)')),
                ('commitment_to_bilingual_education', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Commitment to Bilingual Education')),
                ('commitment_to_bilingual_education_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio1/', verbose_name='Commitment to Bilingual Education (PDF)')),
                ('strategic_planning', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Strategic Planning')),
                ('strategic_planning_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio1/', verbose_name='Strategic Planning (PDF)')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dominio1', to='ia.crm_fui', verbose_name='Nome da Escola')),
            ],
        ),
    ]
