# Generated by Django 5.0.6 on 2024-11-25 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glex', '0004_dominio1'),
        ('ia', '0058_alter_processo_assunto_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dominio2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Culture')),
                ('culture_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio2/', verbose_name='Culture (PDF)')),
                ('safe_and_caring_school', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Safe and Caring School')),
                ('safe_and_caring_school_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio2/', verbose_name='Safe and Caring School (PDF)')),
                ('equity_diversity_inclusion', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Equity, Diversity and Inclusion')),
                ('equity_diversity_inclusion_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio2/', verbose_name='Equity, Diversity and Inclusion (PDF)')),
                ('stakeholder_communication', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Stakeholder Communication')),
                ('stakeholder_communication_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio2/', verbose_name='Stakeholder Communication (PDF)')),
                ('stakeholder_engagement', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Stakeholder Engagement')),
                ('stakeholder_engagement_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio2/', verbose_name='Stakeholder Engagement (PDF)')),
                ('health_and_safety', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Health and Safety')),
                ('health_and_safety_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio2/', verbose_name='Health and Safety (PDF)')),
                ('collection_interpretation_data', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Collection and Interpretation of Whole School Assessment Data')),
                ('collection_interpretation_data_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio2/', verbose_name='Collection and Interpretation of Whole School Assessment Data (PDF)')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dominio2', to='ia.crm_fui', verbose_name='Nome da Escola')),
            ],
        ),
        migrations.CreateModel(
            name='Dominio3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructional_processes_practices', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Instructional Processes and Practices')),
                ('instructional_processes_practices_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio3/', verbose_name='Instructional Processes and Practices (PDF)')),
                ('learning_plans', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Learning Plans')),
                ('learning_plans_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio3/', verbose_name='Learning Plans (PDF)')),
                ('student_centered_learning', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Student Centered Learning')),
                ('student_centered_learning_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio3/', verbose_name='Student Centered Learning (PDF)')),
                ('inclusionary_practices', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Inclusionary Practices')),
                ('inclusionary_practices_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio3/', verbose_name='Inclusionary Practices (PDF)')),
                ('teacher_collaboration', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Teacher Collaboration')),
                ('teacher_collaboration_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio3/', verbose_name='Teacher Collaboration (PDF)')),
                ('classroom_management', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Classroom Management')),
                ('classroom_management_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio3/', verbose_name='Classroom Management (PDF)')),
                ('supervision_evaluation', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Supervision & Evaluation')),
                ('supervision_evaluation_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio3/', verbose_name='Supervision & Evaluation (PDF)')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dominio3', to='ia.crm_fui', verbose_name='Nome da Escola')),
            ],
        ),
        migrations.CreateModel(
            name='Dominio4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_goals_success_criteria', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Learning Goals and Success Criteria')),
                ('learning_goals_success_criteria_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio4/', verbose_name='Learning Goals and Success Criteria (PDF)')),
                ('assessment_strategies_tools', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Assessment Strategies and Tools')),
                ('assessment_strategies_tools_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio4/', verbose_name='Assessment Strategies and Tools (PDF)')),
                ('fair_assessment_practices', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Fair Assessment Practices')),
                ('fair_assessment_practices_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio4/', verbose_name='Fair Assessment Practices (PDF)')),
                ('assessment_triangulation_data', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Assessment and the Triangulation of Data')),
                ('assessment_triangulation_data_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio4/', verbose_name='Assessment and the Triangulation of Data (PDF)')),
                ('reporting_student_achievement', models.IntegerField(choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], verbose_name='Reporting Student Achievement')),
                ('reporting_student_achievement_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/dominio4/', verbose_name='Reporting Student Achievement (PDF)')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dominio4', to='ia.crm_fui', verbose_name='Nome da Escola')),
            ],
        ),
    ]
