# Generated by Django 5.0.6 on 2024-11-26 01:00

import glex.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glex', '0005_dominio2_dominio3_dominio4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominio1',
            name='commitment_to_bilingual_education_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio1, verbose_name='Commitment to Bilingual Education (PDF)'),
        ),
        migrations.AlterField(
            model_name='dominio1',
            name='implementation_supervision_instructional_program_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio1, verbose_name='Implementation and Supervision (PDF)'),
        ),
        migrations.AlterField(
            model_name='dominio1',
            name='professional_learning_opportunities_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio1, verbose_name='Professional Learning Opportunities (PDF)'),
        ),
        migrations.AlterField(
            model_name='dominio1',
            name='program_implementation_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio1, verbose_name='Program Implementation (PDF)'),
        ),
        migrations.AlterField(
            model_name='dominio1',
            name='resource_allocation_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio1, verbose_name='Resource Allocation (PDF)'),
        ),
        migrations.AlterField(
            model_name='dominio1',
            name='staffing_instructional_program_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio1, verbose_name='Staffing the Instructional Program (PDF)'),
        ),
        migrations.AlterField(
            model_name='dominio1',
            name='strategic_planning_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio1, verbose_name='Strategic Planning (PDF)'),
        ),
        migrations.AlterField(
            model_name='dominio2',
            name='collection_interpretation_data_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio2, verbose_name='Collection and Interpretation of Whole School Assessment Data (PDF)'),
        ),
        migrations.AlterField(
            model_name='dominio2',
            name='culture_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio2, verbose_name='Culture (PDF)'),
        ),
        migrations.AlterField(
            model_name='dominio2',
            name='equity_diversity_inclusion_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio2, verbose_name='Equity, Diversity and Inclusion (PDF)'),
        ),
        migrations.AlterField(
            model_name='dominio2',
            name='health_and_safety_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio2, verbose_name='Health and Safety (PDF)'),
        ),
        migrations.AlterField(
            model_name='dominio2',
            name='safe_and_caring_school_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio2, verbose_name='Safe and Caring School (PDF)'),
        ),
        migrations.AlterField(
            model_name='dominio2',
            name='stakeholder_communication_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio2, verbose_name='Stakeholder Communication (PDF)'),
        ),
        migrations.AlterField(
            model_name='dominio2',
            name='stakeholder_engagement_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio2, verbose_name='Stakeholder Engagement (PDF)'),
        ),
        migrations.AlterField(
            model_name='dominio3',
            name='classroom_management_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio3, verbose_name='Classroom Management (PDF)'),
        ),
        migrations.AlterField(
            model_name='dominio3',
            name='inclusionary_practices_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio3, verbose_name='Inclusionary Practices (PDF)'),
        ),
        migrations.AlterField(
            model_name='dominio3',
            name='instructional_processes_practices_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio3, verbose_name='Instructional Processes and Practices (PDF)'),
        ),
        migrations.AlterField(
            model_name='dominio3',
            name='learning_plans_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio3, verbose_name='Learning Plans (PDF)'),
        ),
        migrations.AlterField(
            model_name='dominio3',
            name='student_centered_learning_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio3, verbose_name='Student Centered Learning (PDF)'),
        ),
        migrations.AlterField(
            model_name='dominio3',
            name='supervision_evaluation_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio3, verbose_name='Supervision & Evaluation (PDF)'),
        ),
        migrations.AlterField(
            model_name='dominio3',
            name='teacher_collaboration_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio3, verbose_name='Teacher Collaboration (PDF)'),
        ),
        migrations.AlterField(
            model_name='dominio4',
            name='assessment_strategies_tools_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio4, verbose_name='Assessment Strategies and Tools (PDF)'),
        ),
        migrations.AlterField(
            model_name='dominio4',
            name='assessment_triangulation_data_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio4, verbose_name='Assessment and the Triangulation of Data (PDF)'),
        ),
        migrations.AlterField(
            model_name='dominio4',
            name='fair_assessment_practices_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio4, verbose_name='Fair Assessment Practices (PDF)'),
        ),
        migrations.AlterField(
            model_name='dominio4',
            name='learning_goals_success_criteria_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio4, verbose_name='Learning Goals and Success Criteria (PDF)'),
        ),
        migrations.AlterField(
            model_name='dominio4',
            name='reporting_student_achievement_pdf',
            field=models.FileField(blank=True, null=True, upload_to=glex.models.upload_to_dominio4, verbose_name='Reporting Student Achievement (PDF)'),
        ),
    ]
