# Generated by Django 5.0.6 on 2024-11-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glex', '0006_alter_dominio1_commitment_to_bilingual_education_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominio1',
            name='commitment_to_bilingual_education_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Commitment to Bilingual Education'),
        ),
        migrations.AddField(
            model_name='dominio1',
            name='implementation_supervision_instructional_program_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Implementation and Supervision of the Instructional Program'),
        ),
        migrations.AddField(
            model_name='dominio1',
            name='professional_learning_opportunities_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Professional Learning Opportunities'),
        ),
        migrations.AddField(
            model_name='dominio1',
            name='program_implementation_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Program Implementation'),
        ),
        migrations.AddField(
            model_name='dominio1',
            name='resource_allocation_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Resource Allocation'),
        ),
        migrations.AddField(
            model_name='dominio1',
            name='staffing_instructional_program_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Staffing the Instructional Program'),
        ),
        migrations.AddField(
            model_name='dominio1',
            name='strategic_planning_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Strategic Planning'),
        ),
        migrations.AddField(
            model_name='dominio2',
            name='collection_interpretation_data_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Collection and Interpretation of Whole School Assessment Data'),
        ),
        migrations.AddField(
            model_name='dominio2',
            name='culture_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Culture'),
        ),
        migrations.AddField(
            model_name='dominio2',
            name='equity_diversity_inclusion_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Equity, Diversity and Inclusion'),
        ),
        migrations.AddField(
            model_name='dominio2',
            name='health_and_safety_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Health and Safety'),
        ),
        migrations.AddField(
            model_name='dominio2',
            name='safe_and_caring_school_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Safe and Caring School'),
        ),
        migrations.AddField(
            model_name='dominio2',
            name='stakeholder_communication_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Stakeholder Communication'),
        ),
        migrations.AddField(
            model_name='dominio2',
            name='stakeholder_engagement_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Stakeholder Engagement'),
        ),
        migrations.AddField(
            model_name='dominio3',
            name='classroom_management_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Classroom Management'),
        ),
        migrations.AddField(
            model_name='dominio3',
            name='inclusionary_practices_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Inclusionary Practices'),
        ),
        migrations.AddField(
            model_name='dominio3',
            name='instructional_processes_practices_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Instructional Processes and Practices'),
        ),
        migrations.AddField(
            model_name='dominio3',
            name='learning_plans_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Learning Plans'),
        ),
        migrations.AddField(
            model_name='dominio3',
            name='student_centered_learning_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Student Centered Learning'),
        ),
        migrations.AddField(
            model_name='dominio3',
            name='supervision_evaluation_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Supervision & Evaluation'),
        ),
        migrations.AddField(
            model_name='dominio3',
            name='teacher_collaboration_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Teacher Collaboration'),
        ),
        migrations.AddField(
            model_name='dominio4',
            name='assessment_strategies_tools_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Assessment Strategies and Tools'),
        ),
        migrations.AddField(
            model_name='dominio4',
            name='assessment_triangulation_data_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Assessment and the Triangulation of Data'),
        ),
        migrations.AddField(
            model_name='dominio4',
            name='fair_assessment_practices_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Fair Assessment Practices'),
        ),
        migrations.AddField(
            model_name='dominio4',
            name='learning_goals_success_criteria_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Learning Goals and Success Criteria'),
        ),
        migrations.AddField(
            model_name='dominio4',
            name='reporting_student_achievement_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment for Reporting Student Achievement'),
        ),
        migrations.AlterField(
            model_name='dominio1',
            name='commitment_to_bilingual_education',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Commitment to Bilingual Education'),
        ),
        migrations.AlterField(
            model_name='dominio1',
            name='implementation_supervision_instructional_program',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Implementation and Supervision of the Instructional Program'),
        ),
        migrations.AlterField(
            model_name='dominio1',
            name='professional_learning_opportunities',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Professional Learning Opportunities'),
        ),
        migrations.AlterField(
            model_name='dominio1',
            name='program_implementation',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Program Implementation'),
        ),
        migrations.AlterField(
            model_name='dominio1',
            name='resource_allocation',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Resource Allocation'),
        ),
        migrations.AlterField(
            model_name='dominio1',
            name='staffing_instructional_program',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Staffing the Instructional Program'),
        ),
        migrations.AlterField(
            model_name='dominio1',
            name='strategic_planning',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Strategic Planning'),
        ),
        migrations.AlterField(
            model_name='dominio2',
            name='collection_interpretation_data',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Collection and Interpretation of Whole School Assessment Data'),
        ),
        migrations.AlterField(
            model_name='dominio2',
            name='culture',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='dominio2',
            name='equity_diversity_inclusion',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Equity, Diversity and Inclusion'),
        ),
        migrations.AlterField(
            model_name='dominio2',
            name='health_and_safety',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Health and Safety'),
        ),
        migrations.AlterField(
            model_name='dominio2',
            name='safe_and_caring_school',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Safe and Caring School'),
        ),
        migrations.AlterField(
            model_name='dominio2',
            name='stakeholder_communication',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Stakeholder Communication'),
        ),
        migrations.AlterField(
            model_name='dominio2',
            name='stakeholder_engagement',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Stakeholder Engagement'),
        ),
        migrations.AlterField(
            model_name='dominio3',
            name='classroom_management',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Classroom Management'),
        ),
        migrations.AlterField(
            model_name='dominio3',
            name='inclusionary_practices',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Inclusionary Practices'),
        ),
        migrations.AlterField(
            model_name='dominio3',
            name='instructional_processes_practices',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Instructional Processes and Practices'),
        ),
        migrations.AlterField(
            model_name='dominio3',
            name='learning_plans',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Learning Plans'),
        ),
        migrations.AlterField(
            model_name='dominio3',
            name='student_centered_learning',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Student Centered Learning'),
        ),
        migrations.AlterField(
            model_name='dominio3',
            name='supervision_evaluation',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Supervision & Evaluation'),
        ),
        migrations.AlterField(
            model_name='dominio3',
            name='teacher_collaboration',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Teacher Collaboration'),
        ),
        migrations.AlterField(
            model_name='dominio4',
            name='assessment_strategies_tools',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Assessment Strategies and Tools'),
        ),
        migrations.AlterField(
            model_name='dominio4',
            name='assessment_triangulation_data',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Assessment and the Triangulation of Data'),
        ),
        migrations.AlterField(
            model_name='dominio4',
            name='fair_assessment_practices',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Fair Assessment Practices'),
        ),
        migrations.AlterField(
            model_name='dominio4',
            name='learning_goals_success_criteria',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Learning Goals and Success Criteria'),
        ),
        migrations.AlterField(
            model_name='dominio4',
            name='reporting_student_achievement',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Below Expectations'), (2, '2 - Approaching Expectations'), (3, '3 - Meeting Expectations'), (4, '4 - Exceeding Expectations')], null=True, verbose_name='Reporting Student Achievement'),
        ),
    ]
