# Generated by Django 5.0.6 on 2024-12-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glex', '0007_dominio1_commitment_to_bilingual_education_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base_de_Conhecimento_Geral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('documento_id', models.CharField(max_length=50, unique=True)),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(blank=True, null=True)),
                ('topico', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
