# Generated by Django 5.0.6 on 2024-12-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glex', '0008_base_de_conhecimento_geral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base_de_conhecimento_geral',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='base_de_conhecimento_geral',
            name='documento_id',
        ),
    ]
