# Generated by Django 5.0.6 on 2024-12-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glex', '0009_remove_base_de_conhecimento_geral_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_de_conhecimento_geral',
            name='sub_topico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_de_conhecimento_geral',
            name='topico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
