# Generated by Django 5.0.6 on 2024-12-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glex', '0010_base_de_conhecimento_geral_sub_topico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base_de_conhecimento_geral',
            name='sub_topico',
        ),
        migrations.RemoveField(
            model_name='base_de_conhecimento_geral',
            name='topico',
        ),
    ]
