# Generated by Django 5.0.6 on 2024-12-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glex', '0012_base_de_conhecimento_geral_sub_topico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_de_conhecimento_geral',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
