# Generated by Django 5.0.6 on 2024-09-17 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customusuario_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_count', models.IntegerField(default=0)),
                ('tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
