# Generated by Django 5.0.6 on 2024-12-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_userrequestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusuario',
            name='clickup_api_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token API ClickUp'),
        ),
        migrations.AddField(
            model_name='customusuario',
            name='clickup_list_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='List ID ClickUp'),
        ),
    ]
