# Generated by Django 5.0.6 on 2024-05-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('persona', models.CharField(max_length=100)),
                ('data_resposta', models.DateField()),
                ('unidade', models.CharField(max_length=100)),
                ('questao', models.TextField()),
                ('resposta', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
