# Generated by Django 5.0.6 on 2024-07-28 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0003_beneficio_ferias_folhaponto_salario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRM_FUI',
            fields=[
                ('id_escola', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Escola')),
                ('nome_da_escola', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Escola')),
                ('CNPJ', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('status_da_escola', models.CharField(blank=True, choices=[('operando', 'Operando'), ('implantando', 'Implantando')], max_length=50, null=True, verbose_name='Status da Escola')),
                ('slms_vendidos', models.IntegerField(blank=True, null=True, verbose_name='SLM Vendidos')),
                ('alunos', models.IntegerField(blank=True, null=True, verbose_name='Alunos')),
                ('meta', models.IntegerField(blank=True, null=True, verbose_name='Meta')),
                ('cluster', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cluster')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço Escola')),
                ('cep_escola', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP Escola')),
                ('bairro_escola', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro Escola')),
                ('cidade_da_escola', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade Escola')),
                ('estado_da_escola', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado da Escola')),
                ('regiao_da_escola', models.CharField(blank=True, max_length=100, null=True, verbose_name='Região da Escola')),
                ('telefone_de_contato_da_escola', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone da Escola')),
                ('email_da_escola', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail da Escola')),
                ('segmento_da_escola', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segmento')),
                ('atual_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Atual Série')),
                ('avanco_segmento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Avanço Segmento')),
                ('status_de_adimplencia', models.CharField(blank=True, choices=[('adimplente', 'Adimplente'), ('inadimplente', 'Inadimplente')], max_length=100, null=True, verbose_name='Status de Adimplêcia/Inadimplência')),
                ('ticket_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ticket Medio')),
                ('inadimplencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total do Valor de Inadimplência')),
                ('consultor_comercial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Consultor Comercial')),
                ('consultor_gestao_escolar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Consultor Gestão Escoalr')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_da_resposta', models.DateField(verbose_name='Data da Resposta')),
                ('questao', models.TextField(verbose_name='Questão')),
                ('nota', models.IntegerField(verbose_name='Nota')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_escola', to='ia.crm_fui', verbose_name='Nome da Escola')),
            ],
        ),
    ]
