# Generated by Django 5.0.6 on 2024-07-28 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0004_crm_fui_resposta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resposta',
            new_name='Respostas_NPS',
        ),
    ]
