# Generated by Django 5.0.6 on 2024-07-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0006_respostas_nps_nome_alter_crm_fui_estado_da_escola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm_fui',
            name='status_da_escola',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status da Escola'),
        ),
        migrations.AlterField(
            model_name='crm_fui',
            name='status_de_adimplencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status de Adimplêcia/Inadimplência'),
        ),
    ]
