# Generated by Django 5.0.6 on 2024-07-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0007_alter_crm_fui_status_da_escola_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_fui',
            name='cliente_oculto_2024',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cliente Oculto 2024'),
        ),
        migrations.AddField(
            model_name='crm_fui',
            name='nps_pais_2024_1_onda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='NPS Pais 2024 - 1° Onda'),
        ),
        migrations.AddField(
            model_name='crm_fui',
            name='quality_assurance_2024',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quality Assurance 2024'),
        ),
    ]
