# Generated by Django 5.0.6 on 2024-07-28 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0008_crm_fui_cliente_oculto_2024_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas_SLM_2024',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_do_pedido', models.DateField(verbose_name='Data do Pedido')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade Vendida')),
                ('nome_pais', models.CharField(verbose_name='Nomes dos Pais')),
                ('nome_do_aluno', models.CharField(verbose_name='Nome do Aluno')),
                ('numero_do_pedido', models.CharField(verbose_name='Numero do Pedido')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_escola_venda_slm_2024', to='ia.crm_fui', verbose_name='Nome da Escola Venda 2024')),
            ],
        ),
    ]
