# Generated by Django 5.0.6 on 2024-07-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0009_vendas_slm_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base_de_Conhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, null=True, verbose_name='Título')),
                ('assunto', models.CharField(blank=True, null=True, verbose_name='Assunto')),
                ('sub_assunto', models.CharField(blank=True, null=True, verbose_name='Sub Assunto')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='Texto')),
            ],
        ),
    ]
