# Generated by Django 5.0.6 on 2024-08-04 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0010_base_de_conhecimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crm_fui',
            name='alunos',
        ),
        migrations.AddField(
            model_name='crm_fui',
            name='complemento_escola',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento Escola'),
        ),
        migrations.AddField(
            model_name='crm_fui',
            name='consultor_academico',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Consultor Acadêmico'),
        ),
        migrations.AddField(
            model_name='crm_fui',
            name='consultor_saf',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Consultor SAF'),
        ),
        migrations.AddField(
            model_name='crm_fui',
            name='dias_uteis_entrega_slm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dias Úteis para entrega do SLM'),
        ),
        migrations.AddField(
            model_name='crm_fui',
            name='slms_vendidos_25',
            field=models.IntegerField(blank=True, null=True, verbose_name='SLM Vendidos 2025'),
        ),
        migrations.AddField(
            model_name='crm_fui',
            name='valor_fdmp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total do Valor FDMP'),
        ),
        migrations.AddField(
            model_name='crm_fui',
            name='valor_royalties',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total do Valor dos Royalties'),
        ),
        migrations.AlterField(
            model_name='base_de_conhecimento',
            name='assunto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='base_de_conhecimento',
            name='sub_assunto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sub Assunto'),
        ),
        migrations.AlterField(
            model_name='base_de_conhecimento',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='crm_fui',
            name='consultor_gestao_escolar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Consultor Gestão Escolar'),
        ),
        migrations.AlterField(
            model_name='crm_fui',
            name='slms_vendidos',
            field=models.IntegerField(blank=True, null=True, verbose_name='SLM Vendidos 2024'),
        ),
        migrations.AlterField(
            model_name='respostas_nps',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='vendas_slm_2024',
            name='nome_do_aluno',
            field=models.CharField(max_length=200, verbose_name='Nome do Aluno'),
        ),
        migrations.AlterField(
            model_name='vendas_slm_2024',
            name='nome_pais',
            field=models.CharField(max_length=200, verbose_name='Nomes dos Pais'),
        ),
        migrations.AlterField(
            model_name='vendas_slm_2024',
            name='numero_do_pedido',
            field=models.CharField(max_length=200, verbose_name='Numero do Pedido'),
        ),
        migrations.CreateModel(
            name='Vendas_SLM_2025',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_do_pedido', models.DateField(verbose_name='Data do Pedido 2025')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade Vendida 2025')),
                ('nome_pais', models.CharField(max_length=200, verbose_name='Nomes dos Pais 2025')),
                ('nome_do_aluno', models.CharField(max_length=200, verbose_name='Nome do Aluno 2025')),
                ('numero_do_pedido', models.CharField(max_length=200, verbose_name='Numero do Pedido 2025')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_escola_venda_slm_2025', to='ia.crm_fui', verbose_name='Nome da Escola Venda 2025')),
            ],
        ),
    ]
