# Generated by Django 5.0.6 on 2024-08-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0012_alter_crm_fui_meta_planificador_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificador_2024',
            name='gap_alunos_5k_2024',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='gap_meta_5k_2024',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='meta_5k_2024',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='real_alunos_5k_2024',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='slm_2024_posicao_atual',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='slm_2025',
        ),
    ]
