# Generated by Django 5.0.6 on 2024-08-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0013_remove_planificador_2024_gap_alunos_5k_2024_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificador_2024',
            name='gap_meta_orcamentaria_2024',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='porcentagem_planificador',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='taxa_conversao_acumulada',
        ),
        migrations.AddField(
            model_name='planificador_2024',
            name='data_de_abertura_da_circular_2025',
            field=models.DateField(blank=True, null=True),
        ),
    ]
