# Generated by Django 5.0.6 on 2024-08-09 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0015_planificador_2024_usuario_modificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificador_2024',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nome_escola_planificador', to='ia.crm_fui', verbose_name='Nome da Escola Planificador'),
        ),
    ]
