# Generated by Django 5.0.6 on 2024-08-11 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0016_alter_planificador_2024_escola'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumo_Respostas_NPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.TextField(blank=True, null=True, verbose_name='Resumo')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_escola_resumo_nps', to='ia.crm_fui', verbose_name='Nome da Escola do NPS')),
            ],
        ),
    ]
