# Generated by Django 5.0.6 on 2024-08-21 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0017_resumo_respostas_nps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao_Cliente_Oculto_24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(verbose_name='Pergunta CO24')),
                ('resposta', models.TextField(blank=True, null=True, verbose_name='Comentário Cliente Oculto 24')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_escola_co24', to='ia.crm_fui', verbose_name='Nome da Escola Cliente Oculto 24')),
            ],
        ),
        migrations.CreateModel(
            name='Resumo_Respostas_ClienteOculto24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.TextField(blank=True, null=True, verbose_name='Resumo Cliente Oculto')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_escola_resumo_co24', to='ia.crm_fui', verbose_name='Nome da Escola do resumo do Cliente Oculto 2024')),
            ],
        ),
    ]
