# Generated by Django 5.0.6 on 2024-08-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0018_avaliacao_cliente_oculto_24_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao_cliente_oculto_24',
            name='categoria',
            field=models.TextField(default='', verbose_name='Categoria CO24'),
            preserve_default=False,
        ),
    ]
