# Generated by Django 5.0.6 on 2024-08-23 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0019_avaliacao_cliente_oculto_24_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_Splinklr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ticket', models.IntegerField()),
                ('cliente', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('assunto', models.CharField(max_length=255)),
                ('tempo_medio_de_resposta', models.DurationField()),
                ('tempo_medio_de_primeira_resposta_do_agente', models.DurationField()),
                ('data_ticket', models.DateField()),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_escola_splinklr', to='ia.crm_fui', verbose_name='Nome da Escola Sprinklr')),
            ],
        ),
    ]
