# Generated by Django 5.0.6 on 2024-08-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0020_ticket_splinklr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_splinklr',
            name='tempo_medio_de_primeira_resposta_do_agente',
        ),
        migrations.RemoveField(
            model_name='ticket_splinklr',
            name='tempo_medio_de_resposta',
        ),
        migrations.AddField(
            model_name='ticket_splinklr',
            name='tempo_medio_de_primeira_resposta_do_agente_total',
            field=models.DecimalField(decimal_places=9, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket_splinklr',
            name='tempo_medio_de_resposta_total',
            field=models.DecimalField(decimal_places=9, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
