# Generated by Django 5.0.6 on 2024-08-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0021_remove_ticket_splinklr_tempo_medio_de_primeira_resposta_do_agente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_splinklr',
            name='tempo_medio_de_primeira_resposta_do_agente_total',
            field=models.DecimalField(decimal_places=25, max_digits=50),
        ),
        migrations.AlterField(
            model_name='ticket_splinklr',
            name='tempo_medio_de_resposta_total',
            field=models.DecimalField(decimal_places=25, max_digits=50),
        ),
    ]
