# Generated by Django 5.0.6 on 2024-08-27 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0022_alter_ticket_splinklr_tempo_medio_de_primeira_resposta_do_agente_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_Sprinklr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ticket', models.IntegerField()),
                ('cliente', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('assunto', models.CharField(max_length=255)),
                ('tempo_medio_de_resposta_total', models.DecimalField(decimal_places=25, max_digits=50)),
                ('tempo_medio_de_primeira_resposta_do_agente_total', models.DecimalField(decimal_places=25, max_digits=50)),
                ('data_ticket', models.DateField()),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_escola_sprinklr', to='ia.crm_fui', verbose_name='Nome da Escola da Sprinklr')),
            ],
        ),
    ]
