# Generated by Django 5.0.6 on 2024-08-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0023_ticket_sprinklr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_sprinklr',
            name='tempo_medio_de_primeira_resposta_do_agente_total',
        ),
        migrations.AddField(
            model_name='ticket_sprinklr',
            name='qtd_mensagens_cliente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket_sprinklr',
            name='qtd_mensagens_maple',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket_sprinklr',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket_sprinklr',
            name='assunto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket_sprinklr',
            name='tempo_medio_de_resposta_total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Ticket_Splinklr',
        ),
    ]
