# Generated by Django 5.0.6 on 2024-08-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0024_remove_ticket_sprinklr_tempo_medio_de_primeira_resposta_do_agente_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas_slm_2024',
            name='id_linha',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id da Linha 2024'),
        ),
        migrations.AddField(
            model_name='vendas_slm_2025',
            name='id_linha',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id da Linha 2025'),
        ),
    ]
