# Generated by Django 5.0.6 on 2024-09-04 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0025_vendas_slm_2024_id_linha_vendas_slm_2025_id_linha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_sprinklr',
            name='area',
        ),
        migrations.RemoveField(
            model_name='ticket_sprinklr',
            name='qtd_mensagens_cliente',
        ),
        migrations.RemoveField(
            model_name='ticket_sprinklr',
            name='qtd_mensagens_maple',
        ),
        migrations.RemoveField(
            model_name='ticket_sprinklr',
            name='tempo_medio_de_resposta_total',
        ),
    ]
