# Generated by Django 5.0.6 on 2024-09-06 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0026_remove_ticket_sprinklr_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_fui',
            name='meta_adiantamento_24_25',
            field=models.IntegerField(blank=True, null=True, verbose_name='Meta Adiantamento 2024/2025'),
        ),
        migrations.AlterField(
            model_name='vendas_slm_2024',
            name='id_linha',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Id da Linha 2024'),
        ),
        migrations.AlterField(
            model_name='vendas_slm_2025',
            name='id_linha',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Id da Linha 2025'),
        ),
        migrations.CreateModel(
            name='PedidosAlterados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_aluno', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Aluno')),
                ('numero_do_pedido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Pedido')),
                ('motivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo')),
                ('alterado_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alterado Por')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_alterados', to='ia.crm_fui', verbose_name='Escola')),
            ],
        ),
    ]
