# Generated by Django 5.0.6 on 2024-09-09 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0027_crm_fui_meta_adiantamento_24_25_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita_Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario_visita', models.TextField()),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_escola_comentario_visista', to='ia.crm_fui', verbose_name='Nome da Escola Comentario Visita')),
            ],
        ),
    ]
