# Generated by Django 5.0.6 on 2024-09-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0029_resumo_visita_escola'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificador_2024',
            name='historico_alteracoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
