# Generated by Django 5.0.6 on 2024-09-19 21:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0030_planificador_2024_historico_alteracoes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificador_2024',
            name='historico_alteracoes',
        ),
        migrations.CreateModel(
            name='HistoricoAlteracoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(default=django.utils.timezone.now)),
                ('alteracoes', models.TextField()),
                ('planificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='ia.planificador_2024')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
