# Generated by Django 5.0.6 on 2024-09-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0031_remove_planificador_2024_historico_alteracoes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificador_2024',
            name='meta_orcamentaria_2024',
        ),
    ]
