# Generated by Django 5.0.6 on 2024-09-20 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0033_resumoalteracoes_planificador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificador_2024',
            name='acao_1_elegivel_trade_marketing',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=3, verbose_name='Ação 1 Elegível Trade Marketing'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='acao_1_trade_marketing_acoes_alinhadas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ação 1 Trade Marketing Ações Alinhadas'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='acao_1_trade_valor',
            field=models.FloatField(blank=True, null=True, verbose_name='Ação 1 Trade Valor'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='acao_2_experience_day_09_11_24',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=3, verbose_name='Ação 2 Experience Day 09/11/2024'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='acao_2_experience_day_10_08_24',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=3, verbose_name='Ação 2 Experience Day 10/08/2024'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='acao_2_experience_day_21_09_24',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=3, verbose_name='Ação 2 Experience Day 21/09/2024'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='acao_2_experience_day_24_08_24',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=3, verbose_name='Ação 2 Experience Day 24/08/2024'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='acao_2_experience_day_26_10_24',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=3, verbose_name='Ação 2 Experience Day 26/10/2024'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='acao_3_friend_get_friend',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=3, verbose_name='Ação 3 Friend Get Friend'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='acao_4_webinars_com_autoridades_pos',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=3, verbose_name='Ação 4 Webinars com Autoridades (Pós)'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='acao_4_webinars_com_autoridades_pre',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=3, verbose_name='Ação 4 Webinars com Autoridades (Pré)'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='acao_5_sdr_taxa_conversao_validacao_lead',
            field=models.FloatField(blank=True, null=True, verbose_name='Ação 5 SDR Taxa de Conversão Validação de Lead'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='acao_5_sdr_taxa_conversao_visitas',
            field=models.FloatField(blank=True, null=True, verbose_name='Ação 5 SDR Taxa de Conversão Visitas'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='acao_6_alinhado_resgate_leads',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=3, verbose_name='Ação 6 Alinhado Resgate de Leads'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='acao_6_quantidade_leads_resgatados',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ação 6 Quantidade de Leads Resgatados'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='acao_6_todos_leads_resgatados_contatados',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=3, verbose_name='Ação 6 Todos Leads Resgatados Contatados'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='arvore',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=3, verbose_name='Árvore'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='atingimento_matriculas_2025',
            field=models.FloatField(blank=True, null=True, verbose_name='Atingimento de Matrículas 2025'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='atingimento_real_alunos_2025',
            field=models.FloatField(blank=True, null=True, verbose_name='Atingimento Real de Alunos 2025'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='atingimento_rematriculas_2025',
            field=models.FloatField(blank=True, null=True, verbose_name='Atingimento de Rematrículas 2025'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='base_rematriculaveis_2025',
            field=models.IntegerField(blank=True, null=True, verbose_name='Base de Rematriculáveis 2025'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='circular_oferta_2025_publicado',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=3, verbose_name='Circular de Oferta 2025 Publicado'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='correlacao_alunos_slms_2025',
            field=models.FloatField(blank=True, null=True, verbose_name='Correlação Alunos-SLMS 2025'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='crm_b2c',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=3, verbose_name='CRM B2C'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='data_abertura_matricula_2025',
            field=models.DateField(blank=True, null=True, verbose_name='Data Abertura Matrícula 2025'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='data_atualizacao_resultados',
            field=models.DateField(blank=True, null=True, verbose_name='Data Atualização Resultados'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='data_de_abertura_da_circular_2025',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Abertura da Circular 2025'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='data_implementacao_arvore',
            field=models.DateField(blank=True, null=True, verbose_name='Data Implementação Árvore'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='leads_central_ago_24',
            field=models.IntegerField(blank=True, null=True, verbose_name='Leads Central Agosto 2024'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='leads_escolas_ago_24',
            field=models.IntegerField(blank=True, null=True, verbose_name='Leads Escolas Agosto 2024'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='matriculas_ago_24',
            field=models.IntegerField(blank=True, null=True, verbose_name='Matrículas Agosto 2024'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='mc_2025',
            field=models.FloatField(blank=True, null=True, verbose_name='MC 2025'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='meta_alunos_5k_2024',
            field=models.IntegerField(blank=True, null=True, verbose_name='Meta de Alunos 5K 2024'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='meta_matricula_2025',
            field=models.IntegerField(blank=True, null=True, verbose_name='Meta de Matrícula 2025'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='meta_rematricula_2025',
            field=models.IntegerField(blank=True, null=True, verbose_name='Meta de Rematrícula 2025'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='pedidos_entregues',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pedidos Entregues'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='pedidos_faturados',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pedidos Faturados'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='pedidos_represados_logistica_2025',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pedidos Represados Logística 2025'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='piloto_welcome_baby_bear',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=3, verbose_name='Piloto Welcome Baby Bear'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='real_matricula_2025',
            field=models.IntegerField(blank=True, null=True, verbose_name='Real de Matrícula 2025'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='real_rematriculas_2025',
            field=models.IntegerField(blank=True, null=True, verbose_name='Real de Rematrículas 2025'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='setup_plano_comercial_segundo_semestre',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=3, verbose_name='Setup Plano Comercial Segundo Semestre'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='slm_2022',
            field=models.FloatField(blank=True, null=True, verbose_name='SLM 2022'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='slm_2023',
            field=models.FloatField(blank=True, null=True, verbose_name='SLM 2023'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='slms_2025_m',
            field=models.FloatField(blank=True, null=True, verbose_name='SLMS 2025 (Média)'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='taxa_conversao_atual_leads_visitas',
            field=models.FloatField(blank=True, null=True, verbose_name='Taxa de Conversão Atual Leads-Visitas'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='taxa_conversao_atual_visitas_matriculas',
            field=models.FloatField(blank=True, null=True, verbose_name='Taxa de Conversão Atual Visitas-Matrículas'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='taxa_conversao_leads_matriculas',
            field=models.FloatField(blank=True, null=True, verbose_name='Taxa de Conversão Leads-Matrículas'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='toddle',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=3, verbose_name='Todle'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='toddle_planejamento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Todle Planejamento'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='toddle_portfolio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Todle Portfólio'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='total_meta_alunos_2025',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Meta de Alunos 2025'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='total_real_alunos_2025',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Real de Alunos 2025'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='ultima_data_atualizacao_bloc_drivers_comerciais_estrategicos',
            field=models.DateField(blank=True, null=True, verbose_name='Última Atualização Bloco Drivers Comerciais Estratégicos'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='ultima_data_atualizacao_bloc_drivers_comerciais_meio',
            field=models.DateField(blank=True, null=True, verbose_name='Última Atualização Bloco Drivers Comerciais Meio'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='ultima_data_atualizacao_bloc_funil_comercial',
            field=models.DateField(blank=True, null=True, verbose_name='Última Atualização Bloco Funil Comercial'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='usuario_modificacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Modificação'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='visitas_ago_24',
            field=models.IntegerField(blank=True, null=True, verbose_name='Visitas Agosto 2024'),
        ),
    ]
