# Generated by Django 5.0.6 on 2024-09-27 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0035_resumo_respostas_clienteoculto24_geral_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resumo_Respostas_ClienteOculto24_Geral',
        ),
    ]
