# Generated by Django 5.0.6 on 2024-10-01 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0038_alter_resumo_sac_resumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ouvidoria_SAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_responsavel', models.CharField(blank=True, max_length=255, null=True)),
                ('tema', models.CharField(blank=True, max_length=255, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_reclamacao', models.DateField(blank=True, null=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_escola_ouvidoria', to='ia.crm_fui', verbose_name='Nome da Escola da Ouvidoria')),
            ],
        ),
    ]
