# Generated by Django 5.0.6 on 2024-10-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0041_alter_planificador_2024_se_nao_crm_b2c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificador_2024',
            name='se_nao_crm_b2c',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Se não CRM B2C'),
        ),
    ]
