# Generated by Django 5.0.6 on 2024-10-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0042_alter_planificador_2024_se_nao_crm_b2c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificador_2024',
            name='se_nao_acao_1_elegivel_trade_marketing',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Se não Ação 1 Elegível Trade Marketing'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='se_nao_acao_2_experience_day_09_11_24',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Se não Ação 2 Experience Day 09/11/2024'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='se_nao_acao_2_experience_day_10_08_24',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Se não Ação 2 Experience Day 10/08/2024'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='se_nao_acao_2_experience_day_21_09_24',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Se não Ação 2 Experience Day 21/09/2024'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='se_nao_acao_2_experience_day_24_08_24',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Se não Ação 2 Experience Day 24/08/2024'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='se_nao_acao_2_experience_day_26_10_24',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Se não Ação 2 Experience Day 26/10/2024'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='se_nao_acao_3_friend_get_friend',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Se não Ação 3 Friend Get Friend'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='se_nao_acao_4_webinars_com_autoridades_pos',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Se não Ação 4 Webinars com Autoridades (Pós)'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='se_nao_acao_4_webinars_com_autoridades_pre',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Se não Ação 4 Webinars com Autoridades (Pré)'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='se_nao_acao_6_alinhado_resgate_leads',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Se não Ação 6 Alinhado Resgate de Leads'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='se_nao_acao_6_todos_leads_resgatados_contatados',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Se não Ação 6 Todos Leads Resgatados Contatados'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='se_nao_arvore',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Se não Árvore'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='se_nao_circular_oferta_2025_publicado',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Se não Circular de Oferta 2025 Publicado'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='se_nao_piloto_welcome_baby_bear',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Se não Piloto Welcome Baby Bear'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='se_nao_setup_plano_comercial_segundo_semestre',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Se não Setup Plano Comercial Segundo Semestre'),
        ),
        migrations.AlterField(
            model_name='planificador_2024',
            name='se_nao_toddle',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Se não Todle'),
        ),
    ]
