# Generated by Django 5.0.6 on 2024-10-03 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0043_alter_planificador_2024_se_nao_acao_1_elegivel_trade_marketing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reclamacao', models.DateField(verbose_name='Data Reclamacao')),
                ('origem_reclamacao', models.CharField(choices=[('reclame_aqui', 'Reclame Aqui'), ('fale_maple', 'Fale Maple'), ('social_media', 'Social Media'), ('ouvidoria_seb', 'Ouvidoria SEB'), ('redes_sociais', 'Redes Sociais'), ('outros', 'Outros')], max_length=50, verbose_name='Origem da Reclamacao')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=50, verbose_name='Prioridade')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('nome_responsavel', models.CharField(max_length=255, verbose_name='Nome Responsavel')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('telefones', models.IntegerField(verbose_name='Telefones')),
                ('aluno', models.CharField(max_length=255, verbose_name='Aluno')),
                ('status', models.CharField(choices=[('aguardando_usuario', 'Aguardando retorno usuário'), ('finalizado', 'Finalizado'), ('aguardando_escola', 'Aguardando retorno escola'), ('sem_retorno_escola', 'Sem retorno da escola'), ('escola_nao_retornou', 'Escola não retornou'), ('pendente', 'Pendente'), ('aguardando_responsavel', 'Aguardando retorno do responsável')], max_length=50, verbose_name='Status')),
                ('descricao_reclamacao', models.TextField(verbose_name='Descricao da Reclamacao')),
                ('tem_camera', models.BooleanField(default=False, verbose_name='Tem Camera')),
                ('tem_ata', models.BooleanField(default=False, verbose_name='Tem ATA')),
                ('foi_feita_reuniao_pais', models.BooleanField(default=False, verbose_name='Foi Feita a Reuniao com os Pais')),
                ('tem_testemunha', models.BooleanField(default=False, verbose_name='Tem Testemunha')),
                ('investigacao', models.TextField(verbose_name='Investigacao')),
                ('conclusao_final', models.TextField(verbose_name='Conclusao Final')),
                ('data_conclusao', models.DateField(verbose_name='Data da Conclusao')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_escola_reclamacao', to='ia.crm_fui', verbose_name='Nome da Escola Reclamação')),
            ],
        ),
    ]
