# Generated by Django 5.0.6 on 2024-10-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0044_reclamacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacao',
            name='foi_feita_reuniao_pais',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, verbose_name='Foi Feita a Reunião com os Pais'),
        ),
        migrations.AlterField(
            model_name='reclamacao',
            name='tem_ata',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, verbose_name='Tem ATA'),
        ),
        migrations.AlterField(
            model_name='reclamacao',
            name='tem_camera',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, verbose_name='Tem Câmera'),
        ),
        migrations.AlterField(
            model_name='reclamacao',
            name='tem_testemunha',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, verbose_name='Tem Testemunha'),
        ),
    ]
