# Generated by Django 5.0.6 on 2024-10-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0046_alter_reclamacao_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacao',
            name='nome_responsavel',
            field=models.CharField(default='', max_length=255, verbose_name='Nome Responsavel'),
            preserve_default=False,
        ),
    ]
