# Generated by Django 5.0.6 on 2024-10-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0050_remove_reclamacao_tem_evidencias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacao',
            name='telefones',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True, verbose_name='Telefones'),
        ),
    ]
