# Generated by Django 5.0.6 on 2024-10-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0052_planificador_2024_acao_marketing_offline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificador_2024',
            name='observacoes_equipe_comercial',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Observações sobre a equipe comercial'),
        ),
    ]
