# Generated by Django 5.0.6 on 2024-10-14 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0053_alter_planificador_2024_observacoes_equipe_comercial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificador_2024',
            name='acao_marketing_offline',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='campanhas_mkt_digital_local',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='consultor_campo_guia_mbear_experience',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='equipe_comercial_dedicada_novas_matriculas',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='equipe_comercial_treinamento_central',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='equipe_inscrita_mentoria_vendas',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='escola_possui_equipe_ou_agencia_marketing',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='escola_possui_orcamento_marketing_local',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='investimento_medio_mensal_campanhas_online',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='media_investimentos_marketing_offline',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='motivo_sem_equipe_comercial_novas_matriculas',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='nro_consultores_equipe_comercial',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='observacoes_equipe_comercial',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='orcamento_marketing_anual_medio',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='pesquisa_concorrencia_realizada',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='planejamento_ativacoes_marketing_local',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='preco_material_didatico_ensino_medio_concorrente',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='preco_material_didatico_fundamental_concorrente',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='preco_material_didatico_infantil_concorrente',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='ticket_ensino_medio_concorrente',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='ticket_fundamental_concorrente',
        ),
        migrations.RemoveField(
            model_name='planificador_2024',
            name='ticket_infantil_concorrente',
        ),
    ]
