# Generated by Django 5.0.6 on 2024-11-11 19:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0055_planificador_2024_acoes_ativacao_alunos_sem_slm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_do_processo', models.CharField(blank=True, max_length=255, null=True)),
                ('assunto_principal', models.CharField(blank=True, max_length=255, null=True)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('tipo_do_processo', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_de_tribunal', models.CharField(blank=True, max_length=255, null=True)),
                ('status_do_processo', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_polo_ativo', models.CharField(blank=True, max_length=255, null=True)),
                ('documento_polo_ativo', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_polo_passivo', models.CharField(blank=True, max_length=255, null=True)),
                ('documento_polo_passivo', models.CharField(blank=True, max_length=255, null=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='ia.crm_fui', verbose_name='Nome da Escola do Processo')),
            ],
        ),
        migrations.CreateModel(
            name='Protesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('resultado', models.CharField(blank=True, max_length=255, null=True)),
                ('cartorio', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protestos', to='ia.crm_fui', verbose_name='Nome da Escola do Protesto')),
            ],
        ),
    ]
