# Generated by Django 5.0.6 on 2024-11-26 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0058_alter_processo_assunto_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_linha', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
                ('data_do_pedido', models.DateField()),
                ('serie', models.CharField(max_length=255)),
                ('nome_do_produto', models.CharField(max_length=255)),
                ('codigo_do_produto', models.CharField(max_length=50)),
                ('nome_pais', models.CharField(max_length=255)),
                ('nome_do_aluno', models.CharField(max_length=255)),
                ('pedido', models.CharField(max_length=50)),
                ('status_erp', models.CharField(max_length=50)),
                ('status_logistico', models.CharField(max_length=50)),
                ('status_transportadora', models.CharField(max_length=255)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_escola', to='ia.crm_fui', verbose_name='Nome da Escola pedidos')),
            ],
        ),
    ]
