# Generated by Django 5.0.6 on 2024-12-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0059_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_fui',
            name='nps_pais_2024_2_onda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='NPS Pais 2024 - 2° Onda'),
        ),
        migrations.AddField(
            model_name='crm_fui',
            name='nps_pais_2024_2_onda_engajamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='NPS Pais 2024 - 2° Onda Engajamento'),
        ),
    ]
