# Generated by Django 5.0.6 on 2024-12-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0061_registroia'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
