# Generated by Django 5.0.6 on 2024-12-09 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0062_registroia_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroia',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_ia', to='ia.crm_fui', verbose_name='Escola'),
        ),
        migrations.AlterField(
            model_name='registroia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
